# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.champlain: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# for docker

spring:
  datasource:
    url: jdbc:mysql://mysql1/ateliermecanique-db
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

---
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop


server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000